# Generated by Django 4.1 on 2022-12-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=400, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
